name: CI & Release

on:
  push:
    branches: ["main"]
    tags:
      - "v*.*.*" # trigger saat push tag seperti v0.1.0
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Go environment
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      # Install dependencies
      - name: Download dependencies
        run: go mod tidy

      # Build project
      - name: Build
        run: go build -v -o build/swatantra-node ./cmd/node

      # Run unit tests
      - name: Run tests
        run: go test ./... -v

  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Build binary (Linux)
        run: go build -v -o build/swatantra-node-linux ./cmd/node

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: build/swatantra-node-linux
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # --- Docker Build & Push for Tagged Release ---
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker Image (Tag + Latest)
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/swatantra-node:$TAG .
          docker build -t ${{ secrets.DOCKER_USERNAME }}/swatantra-node:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/swatantra-node:$TAG
          docker push ${{ secrets.DOCKER_USERNAME }}/swatantra-node:latest

  docker-main:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker Image (Latest)
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/swatantra-node:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/swatantra-node:latest
